name: C/C++

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11

    steps:
      - uses: actions/checkout@v4

      - name: Create Build Folder
        run: mkdir build

      - name: Build
        run: conan install -s compiler.libcxx=libstdc++ --build=missing .. && cmake .. && cmake --build ./ --target all --parallel
        working-directory: ./build

      - name: Test
        run: ctest --parallel
        working-directory: ./build

      - name: Exec
        run: ./build/src/cli_client --help
